# Generated by Django 6.0.1 on 2026-03-10 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField(help_text='Generic ID reference to Laravel entity')),
                ('is_anomaly', models.BooleanField()),
                ('anomaly_score', models.FloatField()),
                ('flags', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'ai_anomaly_detections',
            },
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField(help_text='References Laravel user ID')),
                ('session_uuid', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_chatbot_conversations',
            },
        ),
        migrations.CreateModel(
            name='LeavePrediction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.IntegerField(help_text='References Laravel employee ID')),
                ('suggested_start_date', models.DateField()),
                ('suggested_end_date', models.DateField()),
                ('score', models.IntegerField()),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'ai_leave_predictions',
            },
        ),
        migrations.CreateModel(
            name='LoanRiskAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('loan_id', models.IntegerField(blank=True, help_text='References Laravel loan ID', null=True)),
                ('employee_id', models.IntegerField(help_text='References Laravel employee ID')),
                ('safety_score', models.IntegerField()),
                ('probability_of_default', models.FloatField()),
                ('recommendation', models.CharField(max_length=100)),
                ('risk_tier', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ai_loan_risk_assessments',
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(help_text='e.g., ticket, feedback, complaint', max_length=50)),
                ('source_id', models.IntegerField()),
                ('sentiment_score', models.FloatField()),
                ('emotion', models.CharField(max_length=50)),
                ('urgency_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ai_sentiment_analyses',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.IntegerField(help_text='References Laravel employee ID')),
                ('recommended_course_id', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'ai_training_recommendations',
            },
        ),
        migrations.CreateModel(
            name='TurnoverPrediction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.IntegerField(help_text='References Laravel employee ID')),
                ('prediction_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('factors_analyzed', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ai_turnover_predictions',
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot')], max_length=50)),
                ('text', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('entities', models.JSONField(default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.chatbotconversation')),
            ],
            options={
                'db_table': 'ai_chatbot_messages',
            },
        ),
    ]
