# Generated by Django 6.0.1 on 2026-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconversation',
            name='memory',
            field=models.JSONField(default=dict, help_text='Stored context like user name, role, etc.'),
        ),
    ]
