# Generated by Django 6.0.1 on 2026-04-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_chatbotconversation_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanriskassessment',
            name='input_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='loanriskassessment',
            name='session_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanriskassessment',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turnoverprediction',
            name='input_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='turnoverprediction',
            name='session_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='turnoverprediction',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
