export const FRENCH_TRANSLATIONS: Record<string, string> = {
  'Unified Platform': 'Plateforme Unifiée',
  'Workforce hub': 'Hub des équipes',
  'Operations OS': 'Système des opérations',

  'Sign In': 'Se connecter',
  'Sign in': 'Se connecter',
  'Signing in...': 'Connexion en cours...',
  'Sign up': "S'inscrire",
  'Get Started': 'Commencer',
  'Create an account': 'Créer un compte',
  'Create account': 'Créer le compte',
  'Creating account...': 'Création du compte...',
  'Set up your access to the Unified Platform': "Configurez votre accès à la Plateforme Unifiée",
  'Already have an account?': 'Vous avez déjà un compte ?',
  'First Name': 'Prénom',
  'First name': 'Prénom',
  'Last Name': 'Nom',
  'Last name': 'Nom',
  'Passwords do not match': 'Les mots de passe ne correspondent pas',
  'Password must be at least 8 characters': 'Le mot de passe doit contenir au moins 8 caractères',
  'Registration failed. Please try again.': "L'inscription a échoué. Veuillez réessayer.",
  'Enter your company now': 'Accéder à votre entreprise',
  'Welcome back': 'Bon retour',
  'Sign in to continue to your workspace': 'Connectez-vous pour accéder à votre espace de travail',
  "Don't have an account?": "Vous n'avez pas de compte ?",
  'Remember me': 'Se souvenir de moi',
  'Forgot password?': 'Mot de passe oublié ?',
  'Back to login': 'Retour à la connexion',
  'Verify your email': 'Vérifiez votre e-mail',
  "We've sent a 6-digit code to": 'Nous avons envoyé un code à 6 chiffres à',
  'your email': 'votre e-mail',
  'Enter 6-digit code': 'Entrez le code à 6 chiffres',
  'Verify Code': 'Vérifier le code',
  'Verifying...': 'Vérification...',
  "Didn't receive the code?": "Vous n'avez pas reçu le code ?",
  'Sending...': 'Envoi...',
  'Resend code': 'Renvoyer le code',
  'Please enter a valid 6-digit code.': 'Veuillez entrer un code valide à 6 chiffres.',
  'Please enter a valid 6-digit code': 'Veuillez entrer un code valide à 6 chiffres.',
  'Email address is missing. Please login again.':
    "L'adresse e-mail est manquante. Veuillez vous reconnecter.",
  'Email address is missing. Please try again.':
    "L'adresse e-mail est manquante. Veuillez réessayer.",
  'A new verification code has been sent to your email.':
    'Un nouveau code de vérification a été envoyé à votre e-mail.',
  'Failed to resend verification code.':
    "Impossible de renvoyer le code de vérification.",
  'The verification code is invalid or has expired.':
    'Le code de vérification est invalide ou expiré.',
  'Reset your password': 'Réinitialisez votre mot de passe',
  'Enter the reset code and your new password.':
    'Entrez le code de réinitialisation et votre nouveau mot de passe.',
  'Reset Code': 'Code de réinitialisation',
  'Confirm New Password': 'Confirmer le nouveau mot de passe',
  'Reset password': 'Réinitialiser le mot de passe',
  'Resetting password...': 'Réinitialisation du mot de passe...',
  'Password reset successfully!': 'Mot de passe réinitialisé avec succès !',
  'Your password has been reset successfully.':
    'Votre mot de passe a été réinitialisé avec succès.',
  "Didn't receive a code? Request one":
    "Vous n'avez pas reçu de code ? Demandez-en un",
  'Failed to reset password. Please check your code and try again.':
    'Impossible de réinitialiser le mot de passe. Vérifiez votre code et réessayez.',
  'Invalid email or password': 'E-mail ou mot de passe invalide',
  'Unable to reach the backend service. Please check that Laravel is running on port 8000.':
    'Impossible de joindre le service backend. Vérifiez que Laravel fonctionne bien sur le port 8000.',
  'Forgot your password?': 'Mot de passe oublié ?',
  "Enter your email address and we'll send you a code to reset your password.":
    "Saisissez votre adresse e-mail et nous vous enverrons un code pour réinitialiser votre mot de passe.",
  'Send reset code': 'Envoyer le code de réinitialisation',
  'Sending code...': 'Envoi du code...',
  'Enter reset code': 'Entrer le code de réinitialisation',
  'Check your email for the reset code.': 'Vérifiez votre e-mail pour trouver le code de réinitialisation.',
  'If an account exists for that email, a password reset code has been sent.':
    'Si un compte existe pour cet e-mail, un code de réinitialisation a été envoyé.',
  'Failed to send reset code. Please try again.':
    "Échec de l'envoi du code de réinitialisation. Veuillez réessayer.",

  'Next-Generation Workforce Operations': 'Opérations RH nouvelle génération',
  'Manage your company': 'Gérez votre entreprise',
  'intelligently.': 'intelligemment.',
  'Run payroll, employee operations, benefits, approvals, and AI-assisted workflows from one polished control center.':
    "Pilotez la paie, les opérations RH, les avantages, les validations et les workflows assistés par l'IA depuis un centre de contrôle unique.",
  'Unified Workforce': 'Équipe unifiée',
  'Manage all employees, departments, and roles in one centralized hub.':
    'Gérez tous les employés, départements et rôles depuis un hub centralisé.',
  'Smart Organization': 'Organisation intelligente',
  'Automate payroll, leave requests, and track attendance seamlessly.':
    "Automatisez la paie, les demandes de congé et le suivi de présence en toute fluidité.",
  'AI-Driven Insights': "Analyses pilotées par l'IA",
  'Predict turnover and get smart recommendations for your business.':
    'Anticipez le turnover et obtenez des recommandations intelligentes pour votre activité.',

  'Dashboard': 'Tableau de bord',
  'Profile': 'Profil',
  'Leave Requests': 'Demandes de congé',
  'Benefits': 'Avantages',
  'Insurance Hub': "Pôle d'assurance",
  'Notifications': 'Notifications',
  'Settings': 'Paramètres',
  'Admin Command': 'Centre admin',
  'Organization': 'Organisation',
  'Talent Pool': 'Vivier de talents',
  'Leave Queue': 'File des congés',
  'Payroll Engine': 'Moteur de paie',
  'Employee Scores': 'Scores employés',
  'Insurance Claims': "Demandes d'assurance",
  'AI Center': 'Centre IA',
  'Messages': 'Messages',
  'Fraud Lab': 'Laboratoire fraude',
  'Agreements': 'Accords',
  'Social Hub': 'Pôle social',
  'System Alerts': 'Alertes système',
  'RH Oversight': 'Pilotage RH',
  'Employees': 'Employés',
  'Payroll Docs': 'Documents de paie',
  'Compliance': 'Conformité',
  'Team Dashboard': "Tableau de bord d'équipe",
  'My Activity': 'Mon activité',
  'operational hub': 'hub opérationnel',
  'Authorized User': 'Utilisateur autorisé',
  'Access Point': "Point d'accès",
  'Log Out': 'Déconnexion',

  'Signals': 'Signaux',
  'urgent items': 'éléments urgents',
  'Mark all read': 'Tout marquer comme lu',
  'All caught up': 'Tout est à jour',
  'New alerts will appear here instantly.': 'Les nouvelles alertes apparaîtront ici instantanément.',
  'System Update': 'Mise à jour système',
  'Launch Full Inbox': 'Ouvrir la boîte complète',
  'Account Control': 'Gestion du compte',
  'Manage Identity': "Gérer l'identité",

  'Appearance': 'Apparence',
  'Default mode is light. Your choice now follows you from landing page to login and dashboard.':
    "Le mode par défaut est clair. Votre choix vous suit désormais de la page d'accueil jusqu'à la connexion et au tableau de bord.",
  'Light mode': 'Mode clair',
  'Dark mode': 'Mode sombre',
  'Clean default workspace across all pages.': 'Espace de travail clair et propre sur toutes les pages.',
  'Great for long sessions and lower light environments.':
    'Idéal pour les longues sessions et les environnements peu éclairés.',
  'Language': 'Langue',
  'English': 'Anglais',
  'French': 'Français',
  'Save Preferences': 'Enregistrer les préférences',
  'Saving...': 'Enregistrement...',
  'Security': 'Sécurité',
  'All users can change their password here.': 'Tous les utilisateurs peuvent changer leur mot de passe ici.',
  'Current Password': 'Mot de passe actuel',
  'New Password': 'Nouveau mot de passe',
  'Confirm Password': 'Confirmer le mot de passe',
  'Update Password': 'Mettre à jour le mot de passe',
  'Updating...': 'Mise à jour...',
  'Workspace Snapshot': "Aperçu de l'espace",
  'Read-only platform settings pulled from Laravel.':
    'Paramètres de plateforme en lecture seule récupérés depuis Laravel.',
  'Company': 'Entreprise',
  'System': 'Système',
  'Not configured': 'Non configuré',
  'Timezone': 'Fuseau horaire',
  'Locale': 'Langue système',
  'Currency': 'Devise',
  'Settings saved successfully.': 'Paramètres enregistrés avec succès.',
  'Unable to save your settings.': "Impossible d'enregistrer vos paramètres.",
  'Password updated successfully.': 'Mot de passe mis à jour avec succès.',
  'Unable to update your password.': 'Impossible de mettre à jour votre mot de passe.',

  'Account Details': 'Détails du compte',
  'These details appear across the platform and notifications.':
    'Ces informations apparaissent sur toute la plateforme et dans les notifications.',
  'Full Name': 'Nom complet',
  'Your full name': 'Votre nom complet',
  'Email': 'E-mail',
  'Save Profile': 'Enregistrer le profil',
  'Photo & Access': 'Photo et accès',
  'Manage your profile photo and review your current access level.':
    "Gérez votre photo de profil et consultez votre niveau d'accès actuel.",
  'Change Photo': 'Changer la photo',
  'Uploading...': 'Téléversement...',
  'PNG or JPG up to 2 MB.': 'PNG ou JPG jusqu’à 2 Mo.',
  'Account Access': 'Accès au compte',
  'Primary role': 'Rôle principal',
  'Email status': "Statut de l'e-mail",
  'Verified': 'Vérifié',
  'Pending verification': 'Vérification en attente',
  'Profile updated successfully.': 'Profil mis à jour avec succès.',
  'Unable to update your profile right now.': 'Impossible de mettre à jour votre profil pour le moment.',
  'Profile photo updated successfully.': 'Photo de profil mise à jour avec succès.',
  'Unable to upload the new photo.': 'Impossible de téléverser la nouvelle photo.',

  'Refresh': 'Actualiser',
  'Mark All Read': 'Tout marquer comme lu',
  'Notification Center': 'Centre de notifications',
  'All': 'Tous',
  'Unread': 'Non lus',
  'Loading notifications...': 'Chargement des notifications...',
  'No notifications yet.': 'Aucune notification pour le moment.',
  'Update': 'Mise à jour',
  'Read': 'Lu',
  'Open': 'Ouvrir',
  'Review account updates, leave activity, and system alerts in one place.':
    "Consultez les mises à jour du compte, l'activité des congés et les alertes système au même endroit.",

  'Search': 'Rechercher',
  'Save': 'Enregistrer',
  'Cancel': 'Annuler',
  'Close': 'Fermer',
  'Create': 'Créer',
  'Edit': 'Modifier',
  'Delete': 'Supprimer',
  'View': 'Voir',
  'Download': 'Télécharger',
  'Upload': 'Téléverser',
  'Submit': 'Soumettre',
  'Approve': 'Approuver',
  'Reject': 'Rejeter',
  'Pending': 'En attente',
  'success': 'succès',
  'warning': 'alerte',
  'destructive': 'critique',
  'default': 'standard',
  'Approved': 'Approuvé',
  'Rejected': 'Rejeté',
  'Active': 'Actif',
  'Inactive': 'Inactif',
  'Status': 'Statut',
  'Actions': 'Actions',
  'Name': 'Nom',
  'Phone': 'Téléphone',
  'Address': 'Adresse',
  'Password': 'Mot de passe',
  'Role': 'Rôle',
  'Description': 'Description',
  'Notes': 'Notes',
  'Documents': 'Documents',
  'Amount': 'Montant',
  'Date': 'Date',
  'Created': 'Créé',
  'Updated': 'Mis à jour',
  'Total': 'Total',
  'Recently': 'Récemment',
  'just now': "à l'instant",
  'N/A': 'N/D',

  'admin': 'admin',
  'employee': 'employé',
  'manager': 'manager',
  'rh manager': 'gestion rh',
}
