# Generated by Django 6.0.1 on 2026-03-10 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAnomalyDetection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('claim_id', models.IntegerField(help_text='References Laravel claim ID')),
                ('is_anomaly', models.BooleanField()),
                ('anomaly_score', models.FloatField()),
                ('flags', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'insurance_anomaly_detections',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimClassification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('claim_id', models.IntegerField(help_text='References Laravel claim ID')),
                ('document_category', models.CharField(max_length=100)),
                ('medical_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField()),
            ],
            options={
                'db_table': 'insurance_claim_classifications',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimOCR',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('claim_id', models.IntegerField(help_text='References Laravel claim ID')),
                ('extracted_text', models.TextField()),
                ('extracted_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField()),
            ],
            options={
                'db_table': 'insurance_claim_ocr',
            },
        ),
    ]
